// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV0GaNA8WTxjJ2YN5h9UhlU4vPs4h0SYY',
    appId: '1:565817267863:web:3ec95ad7bc694d4a7efbd2',
    messagingSenderId: '565817267863',
    projectId: 'projectsflutter22',
    authDomain: 'projectsflutter22.firebaseapp.com',
    databaseURL: 'https://projectsflutter22-default-rtdb.firebaseio.com',
    storageBucket: 'projectsflutter22.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfAHaQizxtwGoD5B2nEekSkTqOsmFPMnc',
    appId: '1:565817267863:android:be04ca194fc4c1ea7efbd2',
    messagingSenderId: '565817267863',
    projectId: 'projectsflutter22',
    databaseURL: 'https://projectsflutter22-default-rtdb.firebaseio.com',
    storageBucket: 'projectsflutter22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlu73N72b1L3QGxnWuNg9bz8nTqlPV5ic',
    appId: '1:565817267863:ios:0305da6b22dcc3297efbd2',
    messagingSenderId: '565817267863',
    projectId: 'projectsflutter22',
    databaseURL: 'https://projectsflutter22-default-rtdb.firebaseio.com',
    storageBucket: 'projectsflutter22.appspot.com',
    androidClientId: '565817267863-0m46ahbo0c4kb2i978q0c5a44j1lk2rl.apps.googleusercontent.com',
    iosClientId: '565817267863-2nt6ougc876bpftq6tprea4tqnk23jdl.apps.googleusercontent.com',
    iosBundleId: 'com.elvis.developedProjects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlu73N72b1L3QGxnWuNg9bz8nTqlPV5ic',
    appId: '1:565817267863:ios:0305da6b22dcc3297efbd2',
    messagingSenderId: '565817267863',
    projectId: 'projectsflutter22',
    databaseURL: 'https://projectsflutter22-default-rtdb.firebaseio.com',
    storageBucket: 'projectsflutter22.appspot.com',
    androidClientId: '565817267863-0m46ahbo0c4kb2i978q0c5a44j1lk2rl.apps.googleusercontent.com',
    iosClientId: '565817267863-2nt6ougc876bpftq6tprea4tqnk23jdl.apps.googleusercontent.com',
    iosBundleId: 'com.elvis.developedProjects',
  );
}
